#%RAML 1.0
title: Third of several RAMLs that use a person schema
# 
# Uses the same schema (basic-person.json) as service1, named with the
# same RAML type name ("person"). The two services are compatible
# because the two definitions of the same type are identical.

types:
  person: !include basic-person.json

/ws3:
  /person:
    /{id}:
      get:
        responses:
          200:
            body:
              application/json:
                type: person
                example: !include basic-person-example.json
