#%RAML 0.8

# For reasons that I do not fully understand, this schema does not get
# included in the definition of the application/json body for 200
# responses to the get method, as it does in test 02 where it is
# inline. It might be that RAML 0.8 doesn't support this (but RAML 1.0
# does)?

title: simple API  

types:
  fooType: |
    {
      "type": "object",
      "$schema": "http://json-schema.org/draft-03/schema",
      "properties": {
        "title": {
          "type": "string",
          "required": true
        },
        "description": {
          "type": "string"
        }
      }
    }

/foo:
  get:
    queryParameters:
      name:
      bar: {type: number}
      baz: {type: string}
    responses:
      200:
        body:
          application/json:
            type: fooType
