#%RAML 0.8

title: simple API  

schemas:
  - personSchema: !include schemas/person.json

/person:
  get:
    queryParameters:
      name:
      maxCount: {type: number}
      queryString: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: personSchema
