#%RAML 0.8

title: simple API  

schemas:
  - fooSchema: !include schemas/foo.json

/foo:
  get:
    queryParameters:
      name:
      bar: {type: number}
      baz: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: fooSchema
