#%RAML 0.8

title: simple API  
version: v1.1
protocols: [ HTTP, HTTPS ]
baseUri: http://some-site.com/dummy-api

schemas:
  - fooSchema: !include schemas/foo.json

/foo:
  get:
    queryParameters:
      name:
      bar: {type: number}
      baz: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: fooSchema
