#%RAML 0.8

title: API that contains a link-field

schemas:
  - personSchema: !include personWithLink.json

/person:
  get:
    queryParameters:
      name:
      maxCount: {type: number}
      queryString: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: personSchema
