#%RAML 0.8

title: Declaration of a schema that is not used

schemas:
  - topSchema: !include top.json

/person:
  get:
    queryParameters:
      name:
      maxCount: {type: number}
      queryString: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: |
              {
                "type": "object",
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                  "name": {
                    "type": "string"
                  },
                  "@metadata": {
                    "type": "object",
                    "readonly": "true",
                    "$ref": "schemas/metadata.json"
                  }
                }
              }
