#%RAML 0.8

title: Endpoint that has a parameter-name in a terminal component of the path

schemas:
  - personSchema: !include schemas/person.json

/person:
  /{personId}:
    get:
      queryParameters:
        name:
        maxCount: {type: number}
        queryString: {type: string}
      responses:
        200:
          body:
            application/json:
              schema: personSchema
