#%RAML 0.8

title: Schema 1 refers to Schema 2, which refers back to Schema 1

schemas:
  - personSchema: !include personWithLinkAndLoop.json

/person:
  get:
    queryParameters:
      name:
      maxCount: {type: number}
      queryString: {type: string}
    responses:
      200:
        body:
          application/json:
            schema: personSchema
